[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
student_intro_program = "6vv7py4b6QB6UtUnChD1uEWKQs9SJ9RdMAm5H9nUArwV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
